import type { Metadata } from 'next'
import { PageHero } from '@/components/PageHero'

export const metadata: Metadata = { title: 'Partnership Opportunities' }

export default function Page() {
  return (
    <>
      <PageHero heading="Partnership Opportunities" />
      <section className="bg-white py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-bold text-[#0C0297] mb-4">We Need People Like You</h2>
          <p className="text-gray-700 leading-relaxed mb-8">We are actively pursuing partnerships with businesses and organizations in the Greater Pittsburgh area and beyond. We recognize the value that can be generated by connecting students with real life people from the business, nonprofit and public sectors.</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 mb-10">
            {[{t:"Community Sponsor",p:"$20+ or 5 volunteer hours"},{t:"Bronze Sponsor",p:"$250"},{t:"Silver Sponsor",p:"$500"},{t:"Gold Sponsor",p:"$1,000"},{t:"Platinum Sponsor",p:"$2,500"},{t:"Diamond Sponsor",p:"$5,000+"}].map((s)=>(
              <div key={s.t} className="border-l-4 border-[#E8B13B] pl-5 py-3">
                <h3 className="font-bold text-[#0C0297]">{s.t}</h3>
                <p className="text-[#E8B13B] font-semibold text-sm">{s.p}</p>
              </div>
            ))}
          </div>
          <a href="/donate" className="inline-block bg-[#0C0297] text-white font-semibold px-7 py-3 rounded hover:bg-blue-800 transition-colors">Donate Now</a>
        </div>
      </section>
    </>
  )
}
